CREATE TABLE `table1` (
  `id` bigint NOT NULL PRIMARY KEY,

  `log1` varchar(255) DEFAULT NULL, KEY(log1),
  `log2` varchar(255) DEFAULT NULL, KEY(log2),
  `log3` varchar(255) DEFAULT NULL, KEY(log3),
  `log4` varchar(255) DEFAULT NULL, KEY(log4),
  `log5` varchar(255) DEFAULT NULL, KEY(log5),
  
  `string1` varchar(255) DEFAULT NULL,
  `string2` varchar(255) DEFAULT NULL,
  `string3` varchar(255) DEFAULT NULL,
  `string4` varchar(255) DEFAULT NULL,
  `string5` varchar(255) DEFAULT NULL,
  `string6` varchar(255) DEFAULT NULL,
  `string7` varchar(255) DEFAULT NULL,
  `string8` varchar(255) DEFAULT NULL,
  `string9` varchar(255) DEFAULT NULL,
  `string10` varchar(255) DEFAULT NULL,
  `string11` varchar(255) DEFAULT NULL,
  `string12` varchar(255) DEFAULT NULL,
  `string13` varchar(255) DEFAULT NULL,
  `string14` varchar(255) DEFAULT NULL,
  `string15` varchar(255) DEFAULT NULL,
  `string16` varchar(255) DEFAULT NULL,
  `string17` varchar(255) DEFAULT NULL,
  `string18` varchar(255) DEFAULT NULL,
  `string19` varchar(255) DEFAULT NULL,  
  `string20` varchar(255) DEFAULT NULL,
  
  `long1` bigint DEFAULT NULL,
  `long2` bigint DEFAULT NULL,
  `long3` bigint DEFAULT NULL,
  `long4` bigint DEFAULT NULL,
  `long5` bigint DEFAULT NULL,
  `long6` bigint DEFAULT NULL,
  `long7` bigint DEFAULT NULL,
  `long8` bigint DEFAULT NULL,
  `long9` bigint DEFAULT NULL,
  `long10` bigint DEFAULT NULL,
  `long11` bigint DEFAULT NULL,
  `long12` bigint DEFAULT NULL,
  `long13` bigint DEFAULT NULL,
  `long14` bigint DEFAULT NULL,
  `long15` bigint DEFAULT NULL,
  `long16` bigint DEFAULT NULL,
  `long17` bigint DEFAULT NULL,
  `long18` bigint DEFAULT NULL,
  `long19` bigint DEFAULT NULL,
  `long20` bigint DEFAULT NULL,
  
  `lob1` longtext,
  `lob2` longtext,
  `lob3` longtext,
  `lob4` longtext,
  `lob5` longtext,
  `lob6` longtext,
  `lob7` longtext,
  `lob8` longtext,
  `lob9` longtext,
  `lob10` longtext,
  `lob11` longtext,
  `lob12` longtext,
  `lob13` longtext,
  `lob14` longtext,
  `lob15` longtext,
  `lob16` longtext,
  `lob17` longtext,
  `lob18` longtext,
  `lob19` longtext,
  `lob20` longtext
  
) ENGINE=InnoDB;